"""Assemble the COMPLETE engines x frameworks x step-strategies summary.

Sources (dense, n=256, k=256, Wmax=64, seed 42, 105 matrices, first 5 dropped):
  min    : euler_exp/eng_{pre}_dense_d4  (BvN + Euler d1-d4)
           run/step_strategy_2026/{dir}  cols {pre}_min_{b}_*   (Radix)
  median : euler_exp/strat_median_{pre}  (BvN + Euler)
           run/step_strategy_2026/{dir}  cols {pre}_median_{b}_*
  max    : euler_exp/strat_max_{pre}     (BvN + Euler)
           run/step_strategy_2026/{dir}  cols {pre}_max_{b}_*

Runtime convention: BvN = bvn_runtime; Radix = max-plane time; Euler = split + max-leaf.
Prints the table and writes paper/strategy_full_table.tex (4 per-engine tabulars).
"""
import glob
import pandas as pd

ROOT = "C:/Users/ofekc/Desktop/Msc/Thesis/bvn_project"
ENG = [("Hungarian", "max", "maximum"), ("WFA", "wfa", "wfa"),
       ("GW Dynamic", "heavy", "heavy"), ("GW Static", "heavy_static", "heavy_static")]
FRAMES = ["BvN"] + [f"B{b}" for b in [16, 8, 4, 2]] + [f"d{d}" for d in [1, 2, 3, 4]]

def latest(pattern):
    return sorted(glob.glob(pattern))[-1]

def euler_src(strategy, pre):
    if strategy == "min":
        return latest(f"{ROOT}/euler_exp/eng_{pre}_dense_d4/*/results_stats.csv")
    return latest(f"{ROOT}/euler_exp/strat_{strategy}_{pre}/*/results_stats.csv")

def cells(strategy, dirname, pre):
    de = pd.read_csv(euler_src(strategy, pre)).iloc[5:]
    dr = pd.read_csv(latest(f"{ROOT}/run/step_strategy_2026/{dirname}/*/results_stats.csv")).iloc[5:]
    out = {"BvN": (de["bvn_runtime"].mean()*1000, de["bvn_cycle"].mean(), de["bvn_perms"].mean())}
    for b in [16, 8, 4, 2]:
        k = f"{pre}_{strategy}_{b}"
        out[f"B{b}"] = (dr[f"{k}_time"].mean()*1000, dr[f"{k}_cycle"].mean(), dr[f"{k}_perms"].mean())
    for d in [1, 2, 3, 4]:
        k = f"euler_heuristic_depth{d}"
        out[f"d{d}"] = ((de[f"{k}_time"].mean()+de[f"{k}_split"].mean())*1000,
                        de[f"{k}_cycle"].mean(), de[f"{k}_perms"].mean())
    return out

data = {name: {s: cells(s, dirname, pre) for s in ["min", "median", "max"]}
        for name, dirname, pre in ENG}

# ---------- console table ----------
for name in data:
    print(f"\n=== {name} ===")
    print(f"{'':6s}" + "".join(f"|{s:^24s}" for s in ["min", "median", "max"]))
    print(f"{'frame':6s}" + "|{:>8s}{:>8s}{:>8s}".format("rt(ms)", "C", "N")*3)
    for fr in FRAMES:
        row = f"{fr:6s}"
        for s in ["min", "median", "max"]:
            rt, c, n = data[name][s][fr]
            row += f"|{rt:8.1f}{c:8.0f}{n:8.0f}"
        print(row)

# ---------- latex fragment ----------
tex = ["% AUTO-GENERATED by build_full_strategy_table.py -- do not edit by hand"]
for name in data:
    tex.append(r"\par\smallskip\textbf{%s}\par\nopagebreak\smallskip" % name)
    tex.append(r"\begin{tabular}{l rrr rrr rrr}")
    tex.append(r"\toprule")
    tex.append(r" & \multicolumn{3}{c}{\textbf{min}} & \multicolumn{3}{c}{\textbf{median}} & \multicolumn{3}{c}{\textbf{max}} \\")
    tex.append(r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}")
    tex.append(r"Config & rt(ms) & $C$ & $N$ & rt(ms) & $C$ & $N$ & rt(ms) & $C$ & $N$ \\")
    tex.append(r"\midrule")
    for fr in FRAMES:
        cs = []
        for s in ["min", "median", "max"]:
            rt, c, n = data[name][s][fr]
            cs += [f"{rt:.0f}", f"{c:,.0f}", f"{n:,.0f}"]
        tex.append(fr.replace("B", "B") + " & " + " & ".join(cs) + r" \\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}\par\medskip")
open("C:/Users/ofekc/Desktop/Msc/Thesis/paper/strategy_full_table.tex", "w", encoding="utf-8").write("\n".join(tex))
print("\nwrote paper/strategy_full_table.tex")
